### ISSUE TITLE
Consider using JWT

### ISSUE THREAD

**Issue by vast** [fs/rails-base-api#154]
For more info see:

* http://angular-tips.com/blog/2014/05/json-web-tokens-introduction/
* http://adamalbrecht.com/2014/12/04/add-json-web-token-authentication-to-your-angular-rails-app/
* https://www.youtube.com/watch?v=_CAq-F2icp4

**Comment by dmitrytrager** [comment]
@timurvafin do you think we need JWT?

**Comment by timurvafin** [comment]
@dmitrytrager I did not dig into the details yet, could you please describe what is all about on the next demo may be?

**Comment by dmitrytrager** [comment]
@timurvafin this does not look like demo stuff
I can provide some details here or in hipchat if you wish)
