### ISSUE TITLE
PaginatedArraySerializer with active_model_serializers (0.9.3)

### ISSUE THREAD

**Issue by spodlecki** [fs/rails-base-api#158]
Using PaginatedArraySerializer, with active_model_serializers (0.9.3) -- the initialize looks like it has changed.

After changing the PaginatedArraySerializer code to
```
def initialize(object, options = {})
      options.merge!({
        meta: {
          pagination: {
            total: object.total_count,
            per_page: object.limit_value,
            page: object.current_page
          }
        }
      })

      super(object, options)
end
```

All specs pass

**Comment by timurvafin** [comment]
@spodlecki could you please create pull request with these changes? Thank you!

**Comment by spodlecki** [comment]
https://github.com/fs/rails-base-api/pull/159

**Please note the deletion of a patch**. Unfortunately I didn't see any specs for that file so I can only assume it was used for including associations to the json response.
