### ISSUE TITLE
Extract authentication_token from UserSerializer

### ISSUE THREAD

**Issue by VladimirMikhailov** [fs/rails-base-api#201]
In order to avoid possible auth token leaks, probably it would be better to extract it from `UserSerializer` into separate `SessionSerializer` and explicitly respond with the `SessionSerializer` only from `SessionController`:

``` ruby
respond_with(user, serializer: SessionSerializer)
```

There're many cases when we could respond with the user or creator of a resource in index actions.
For the instance, it could be a list of plain articles with the article authors like:

``` ruby
class ArticleSerializer < ActiveModel::Serializer
  attributes :name

  has_one :user
end
```

and by default, the activemodel serializer uses `UsersSerializer` which would have sensitive data (authentication_token).

My suggestion here is to extract auth token and keep user serializer only for common user info. What do you think?

**Comment by timurvafin** [comment]
@VladimirMikhailov that all look's very logical! Let's do this!

**Comment by ruslankhaertdinov** [comment]
@timurvafin Let me do this
