### ISSUE TITLE
Nest foreign key relations

### ISSUE THREAD

**Issue by timurvafin** [fs/rails-base-api#96]
Serialize foreign key references with a nested object, e.g.:

``` javascript
{
  "name": "service-production",
  "owner": {
    "id": "5d8201b0..."
  },
  ...
}
```

**Comment by dmitrytrager** [comment]
is this issue still relevant?

**Comment by timurvafin** [comment]
I still like this idea, but not sure it could be implemented in simple way.

**Comment by ruslankhaertdinov** [comment]
@timurvafin Just recheck: the task is still relevant?
